### PR TITLE
Stackable hook system

### PR DESCRIPTION
**Pull request by Leo40Git**
Done by @20kdc, but he's PR-shy so I'm doing it for him.
Allows proper hooking instead of overwriting sections of code.
Codename: "I Can't Believe It's Not GSA2!"
(Commit https://github.com/Clownacy/Cave-Story-Mod-Loader/pull/29/commits/cae318c20bd7b8952606ab43bf433c1b07389ab6 is by me, the rest are by 20kdc)

### CODE REVIEW

**Comment by Clownacy** [comment]
Right, if I'm going to add this, I'd rather the mod loader be put under an open-source license. Maybe LGPL3. Would you mind asking 20kdc to put his code under an LGPL3-compatible license?

**Comment by Leo40Git** [comment]
👍

**Comment by 20kdc** [comment]
Ok, I release all *my* code/changes on this project into the public domain, thus allowing you to relicense it however you wish.
If there's anything I specifically have to do to state this, tell me.

**Comment by Clownacy** [comment]
I'll have to think more on the licensing thing. If I put it under LGPL, then anyone who uses it in their mods would have to distribute the source to the mod loader with their mods. I wouldn't want that. Sure, permissive licenses don't ask for that, but I like the 'you must make the source to modified versions available' thing.

Maybe the linking exception was made for situations like this.

**Pull request merged**
